[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

[dependencies]
onig = "6.4.0"
regex = { version = "1.10.2", features = [] }
clap = { version = "4.4.10", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
num = "0.4.1"
itertools = "0.12.0"