[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["MattBarkway <contact@mattbarkway.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
regex = "^2023.10.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
